ENABLE_GROUP_PERMISSIONS =  False

FORMATTER_TYPES = {}
FORMATTER_FIELD_SUFFIX = '%s_fmt'
FORMATTER_MODULE_NAME = 'format'

VIEW_MODULE_NAME = 'viewset'

TRANSLATOR_MODULE_NAME = 'translate'

MODELTREE_CONF = None

DEFAULT_COLUMN_ORDERING = None
DEFAULT_COLUMNS = None